### PR TITLE
add gomod support // tag v0.0.1.

### PR DESCRIPTION
**Pull request by raulk**

### CODE REVIEW

**Comment by raulk** [comment]
@hsanjuan – could you have a look at the failure in the gomod build task in CI? It's using master of ugorji/go. Is that maybe where the problem is?

**Comment by hsanjuan** [comment]
Doesn't look pretty. Can you set it to https://github.com/ugorji/go/commit/f26fc641ec9d52a2161443cf9bb9fd53b9062a22 instead?

**Comment by hsanjuan** [comment]
That library supports go mod though, you can also  set to the latest tag and I'll figure out where that panic is coming from next week.

**Comment by raulk** [comment]
Thanks for providing the commit sha1 to pin. I'm gonna cut a v0.0.1 gomod release based on our current usage of dependencies. Feel free to do the upgrade, fix the panic, and release a v0.0.2 subsequently.

**Pull request merged**
